spring:
  datasource:
    url: jdbc:h2:tcp://localhost/./shop
    username: sa
    password: 123
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true   // system.out으로 출력 <--> org.hibernate.SQL: debug 로그로 출력
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace